[build]
  publish = "."
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/audio/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"
